#!/bin/bash

# Exit on first error
set -e

# Go to the top level directory of the repository
cd "$(git rev-parse --show-toplevel)"

# Use the environment variable if available
SHELLCHECK="${SHELLCHECK:-shellcheck}"

# Print the version only in CI
[[ "${TRAVIS}" == 'true' ]] && "${SHELLCHECK}" --version

# Run
"${SHELLCHECK}" --shell=bash -- ./check ./fmt ./*.sh ./tests/*.bats
