#!/bin/bash

# Exit on first error
set -e

# Go to the top level directory of the repository
cd "$(git rev-parse --show-toplevel)"

# Use the environment variable if available
SHELLCHECK="${SHELLCHECK:-shellcheck}"

# Print shellcheck version information only in CI
[[ "${TRAVIS}" == 'true' ]] && "${SHELLCHECK}" --version

# Lint with shellcheck
"${SHELLCHECK}" --shell=bash -- "$0" ./*.sh ./test/*.bats
